module.exports = {
  apps: [
    {
      name: 'pakki-rest-env',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      autorestart: true,
      watch: true,
      ignore_watch: ['src/helpers/Guias/**/*.pdf'],
      max_memory_restart: '1G',
      env: {
        PORT:4000,
        PATH_GUIA: '/var/www/devback/Pakki_Rest/src/helpers/Guias',
        URL_GUIA: 'https://devfront.pakki.click/guias',
        //URL_GUIA: 'D:/Desarrollo/Pakki/Pakki_Rest/src/helpers/Guias/Document', //'https://devfront.pakki.click/guias',
        ROOT_API:'/api/v1',
        ENVIROMENT:'Development Server',
        MONGO_URL:'mongodb://127.0.0.1:27017/devpakkiDB',
        USERDB:'devappakki',
        PWDDB:'4Pp4kk1',        
        UPS_CONFIRMATION_URL:'https://wwwcie.ups.com/ups.app/xml/ShipConfirm',
        UPS_ACCEPT_URL:'https://wwwcie.ups.com/ups.app/xml/ShipAccept',
        UPS_QUOTATION_URL:'https://onlinetools.ups.com/ups.app/xml/Rate',
        DHL_URL:'https://xmlpitest-ea.dhl.com/XMLShippingServlet',
        DHL_QUOTATION_URL:'https://xmlpitest-ea.dhl.com/XMLShippingServlet',
        CDR_GUIA_URL:'https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php',
        CDR_ACCEPT_URL:'https://sandbox.coordinadora.com/ags/1.5/server.php',
        CDR_QUOTATION_URL:'https://ws.coordinadora.com/ags/1.5/server.php',
        DHL_USER:'v62_Nn2MH5fRJ7',
        DHL_PASSWORD:'eFnOICjJvP',
        DHL_ACCOUNT_NUMBER:'683061501',
        UPS_USER:'YoTraigo.com',
        UPS_PASSWORD:'Colombia@123',
        UPS_ACCOUNT_NUMBER:'CD393505DC755C88',
        UPS_BILLSHIPPER:'7359XW',
        FDX_ACCOUNT_CO: '203128530',
        CDR_USER:'9c6ca50c-1bba-11eb-adc1-0242ac120002',
        CDR_PASSWORD:'sN7eX7sX3xF1tD4g',
        CDR_ACCOUNT_NUMBER:'901154626',
        CDR_USER_SHIP:'yotraigo.ws',
        CDR_PASSWORD_SHIP:'b980f931e3f9e0f73742431fc4b4d27f096f3912efc894c5a657b078eee32364',
        CDR_ACCOUNT_NUMBER_SHIP:'34557',
        JWT_SECRET:'**Enl4c4s4d3p1n0ch0t0d0scu3nt4nh4st40ch0@@',
        API_FDX_SPS:'http://localhost:4010/sps',
        API_FDX_QTS:'http://localhost:4010/qts',
        API_FDX_PKP:'http://localhost:4010/pkp',        
      },
    },
    {
      name: 'pakki-rest-prod',
      script: 'npm',
      args: 'run prod',
      instances: 1,
      autorestart: true,
      watch: true,
      ignore_watch: ['src/helpers/Guias/**/*.pdf'],
      max_memory_restart: '1G',
      prod: {
        PORT: 3000,
        PATH_GUIA: '/var/www/devback/Pakki_Rest/src/helpers/Guias',
        URL_GUIA:'https://pakki.click/guias',
        ROOT_API:'/api/v1',
        ENVIROMENT:'Production Server',
        MONGO_URL:'mongodb://127.0.0.1:27017/pakkiDB',
        USERDB:'prodppakki',
        PWDDB:'4Pp4kk1',
        JWT_SECRET:'**Enl4c4s4d3p1n0ch0t0d0scu3nt4nh4st40ch0@@',        
        UPS_CONFIRMATION_URL:'https://onlinetools.ups.com/ups.app/xml/ShipConfirm',
        UPS_ACCEPT_URL:'https://onlinetools.ups.com/ups.app/xml/ShipAccept',
        UPS_QUOTATION_URL:'https://onlinetools.ups.com/ups.app/xml/Rate',
        DHL_URL:'https://xmlpi-ea.dhl.com/XMLShippingServlet',
        DHL_QUOTATION_URL:'https://xmlpi-ea.dhl.com/XMLShippingServlet',
        CDR_GUIA_URL:'https://guias.coordinadora.com/ws/guias/1.6/server.php',
        CDR_ACCEPT_URL:'https://wwwcie.CDR.com/CDR.app/xml/ShipAccept',
        CDR_QUOTATION_URL:'https://ws.coordinadora.com/ags/1.5/server.php',
        DHL_USER:'v62_iLVCAT5cjw',
        DHL_PASSWORD:'LH3CQXO7Bn',
        DHL_ACCOUNT_NUMBER:'683061501',
        UPS_USER:'YoTraigo.com',
        UPS_PASSWORD:'Colombia@123',
        UPS_ACCOUNT_NUMBER:'CD393505DC755C88',
        UPS_BILLSHIPPER:'7359XW',
        FDX_ACCOUNT_CO: '203128530',
        CDR_USER:'9c6ca50c-1bba-11eb-adc1-0242ac120002',
        CDR_PASSWORD:'sN7eX7sX3xF1tD4g',
        CDR_ACCOUNT_NUMBER: '901154626',
        CDR_USER_SHIP:'yotraigo.ws',
        CDR_PASSWORD_SHIP:'b980f931e3f9e0f73742431fc4b4d27f096f3912efc894c5a657b078eee32364',
        CDR_ACCOUNT_NUMBER_SHIP: '34557',
        API_FDX_SPS:'http://localhost:4011/sps',
        API_FDX_QTS:'http://localhost:4011/qts',
        API_FDX_PKP:'http://localhost:4011/pkp',
      }
    }    
  ]
};